// <auto-generated />
using System;
using Alta.EFCore.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alta.EFCore.Migrations
{
    [DbContext(typeof(AltaContext))]
    [Migration("20220510163032_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Alta.Entities.POCOs.HeartbeatInitiate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDatetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("MessageReceived")
                        .HasColumnType("varchar(MAX)");

                    b.Property<DateTime>("ResponseDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TranDT")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TranId")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("WCSId")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("WHId")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("HeartbeatInitiates");
                });

            modelBuilder.Entity("Alta.Entities.POCOs.RequestInitiate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDatetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("HasConcluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LODNum")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Line")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MessageReceived")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("MessageSent")
                        .HasColumnType("varchar(MAX)");

                    b.Property<bool>("Noted")
                        .HasColumnType("bit");

                    b.Property<string>("RequestContentsFlag")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RequestStolocFlag")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ResponseDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TranDT")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TranId")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("WCSId")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("WHId")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("RequestInitiates");
                });
#pragma warning restore 612, 618
        }
    }
}
